/** §1 红线：UI 文案全部中文、集中于此。 */
export const S = {
  appName: '2youg1的MD2Prompt',
  emptyPlaceholder: '打开或新建文档',
  emptyHint: '使用顶栏打开本地 Markdown / JSONL / XML 文件，或新建空白文档。',
  noFile: '未打开文档',
  settings: '设置',
  feedback: 'https://github.com/kaile9',

  // 大纲（左栏）
  outlineTitle: '大纲',
  outlineEmpty: '打开文档后，大纲显示在此处。',
  outlineNoHeadings: '本文档没有标题。',
  outlineXml: 'XML 文档（整体为一个代码块）',

  // 修订面板（右栏）
  changesTitle: '修订',
  changesNone: '打开文档后，修订显示在此处。',
  changesEmpty: '暂无未决修订。',
  grpB: '批注请求（B 类）',
  grpA: '直接修改（A 类）',
  grpHidden: '已隐藏',
  grpC: '已撤回（C 类 · 墓碑）',
  pending: (n: number, b: number, a: number, h: number, w: number): string =>
    n ? `待决 ${n} 条 · B ${b} / A ${a}${h ? ` · 隐 ${h}` : ''}${w ? ` · 撤 ${w}` : ''}` : w ? `墓碑 ${w} 条` : '无待决修订',
  tabRev: '修订',
  tabNote: '批注',
  tabTomb: '墓碑',
  hideAll: '全部隐藏',
  hide: '隐藏',
  unhide: '显示',
  withdraw: '撤回',
  withdraw2: '确认撤回',
  cancelWd: '取消',
  restore: '复活',
  clearWd: '清空',
  editNote: '改注',
  expandTip: '点击展开/收起全文',
  jump: '跳转',
  collapse: '收起',
  expand: '展开',
  lineLabel: (n: number): string => `行 ${n}`,
  opReplace: '改',
  opInsert: '增',
  opDelete: '删',
  opMove: '移',
  opNote: '注',

  // 导出
  copyPrompt: '复制 Prompt',
  dlPrompt: '下载 Prompt.md',
  dlClean: '下载干净副本',
  dlPdf: '导出 PDF',
  copied: '已复制',
  failed: '失败',

  // 设置
  settingsTitle: '排版与主题',
  setTheme: '主题',
  themeNight: '纯黑',
  themeMarble: '云石',
  themePaper: '暖纸',
  setStyle: '风格',
  styleGeek: '极客 · 紧凑',
  styleHumanist: '人文 · 宽松',
  setFontSize: '字号',
  setFontWeight: '字重',
  setBrightness: '亮度',
  setContrast: '对比度',
  setGuideLines: '引导线',
  setProgress: '进度',
  progressBar: '细条',
  progressMap: 'minimap',
  progressOff: '关',
  freeNumHint: '可输任意值',
  setLineHeight: '行距',
  setMeasure: '页宽',
  setJustify: '两端对齐',
  setIndent: '首行缩进',
  indentOff: '关闭',
  indentRender: '仅渲染',
  indentWrite: '写入文档',
  setGutter: '行号栏',
  setShortcuts: '快捷键',
  scHint: '点输入框后按键录入；Backspace 恢复默认',
  scLabel: {
    bold: '加粗',
    italic: '斜体',
    strike: '删除线',
    annotate: '批注',
    moveUp: '段落上移',
    moveDown: '段落下移',
    sourceToggle: '源码/渲染切换',
  } as Record<string, string>,
  setFontCjk: '中文字体',
  setFontLatin: '西文字体',
  setDirPrefix: '路径前缀',
  dirPrefixPh: '可选：文档目录，复制路径时拼出完整路径',
  fontFollow: '跟随风格',
  fontCustom: '自定义…',
  fontCjkHei: '黑体（屏显）',
  fontCjkSong: '宋体（纸质）',
  fontCjkKai: '楷体',
  fontLatinSans: '无衬线',
  fontLatinSerif: '衬线',
  fontLatinMono: '等宽（打字机）',
  fontCustomPh: '字体栈，如 "Songti SC", serif',
  resetPrefs: '恢复默认',
  close: '关闭',
  feedbackLabel: '问题反馈',

  // 通用
  save: '保存',
  cancel: '取消',
  preview: '预览',

  // 编辑器/渲染
  image: '图片',
  syntaxError: '语法错误',
  mermaidSource: 'Mermaid 源码',
  mathSource: 'LaTeX 公式',
  htmlImg: '图片标签',
  noFootnote: '未找到脚注定义',

  // 顶栏与保存状态
  openFile: '打开',
  newFile: '新建',
  modeSource: '〈/〉 源码',
  modeSplit: '◫ 分屏',
  modeRender: '✦ 渲染',
  coachTitle: '三步上手',
  coachSteps: [
    '点左上角「打开」，选你的 .md / .jsonl / .xml 文档（允许目录授权后，修改日记会自动存到同目录）。',
    '直接像 Word 一样改；每处修改在右侧「修订」栏成卡——可隐藏、可两段撤回、可跳转。',
    '改完点「复制 Prompt」发给 AI；AI 改完的新版本再打开，之前的修改记录会自动恢复。',
  ],
  coachGo: '开始使用',
  savedOk: '已存',
  saving: '写入中…',
  saveFailed: '保存失败',

  // 顶栏（光标行列）与路径行（修订面板内）
  cursorPos: (l: number, c: number): string => `行 ${l} · 列 ${c}`,
  pathDoc: '文档',
  pathPrompt: '日记',
  pathNote: '点击展开/收起；⧉ 复制路径（浏览器不暴露绝对路径，在设置里填「路径前缀」后复制即为完整路径）',
  pathCopy: '复制路径',
  printHeadFmt: (t: string): string => `源文件完成于 ${t}`,
  printFootFmt: (t: string): string => `导出于 ${t} · 2youg1的MD2Prompt`,

  // JSONL 记录
  recordTitle: '记录',
  recordForm: '表单',
  recordJson: 'JSON',
  recordNotePh: '附一条批注（可选，B 类）',
  recordEmpty: '（空记录）',
  recordAdd: '+ 新增记录',

  // 批注与恢复
  annotate: '批注',
  tbH1: '一级标题',
  tbH2: '二级标题',
  tbH3: '三级标题',
  tbQuote: '引用块',
  tbBullet: '无序列表',
  tbOrdered: '有序列表',
  tbCodeblock: '代码块',
  tbHr: '分割线',
  tbLink: '插入链接',
  tbImage: '插入图片',
  tb_bold: '加粗（选区）',
  tb_italic: '斜体（选区）',
  tb_strike: '删除线（选区）',
  tb_code: '行内代码（选区）',
  tb_link: '链接（选区）',
  tb_annotate: '批注（选区）',
  tbSeedText: '文字',
  tbSeedImage: '图片',
  tbUrlImage: '图片路径或 URL',
  restored: '已恢复未决修订',
  restoreFailed: '恢复失败，已按新基线打开',
  hashMismatch: '同目录 Prompt.md 与文档哈希不符（文档可能已被外部更新）。如何处理？',
  restoreNewBase: '以当前文件为新基线',
  restoreTry: '仍尝试恢复',
  restoreIgnore: '忽略',
} as const;
